### ISSUE TITLE
make package fails on "Unable to resolve entry class"

### ISSUE THREAD

**Issue by Artaud** [danielsiwiec/garmin-connect-seed#3] opened 2017-02-06 11:47 UTC
Hi, when I try to package my app, I'm getting

```
com.garmin.monkeybrains.asm.AssemblerException: Unable to resolve entry class. Check the manifest file.
	at com.garmin.monkeybrains.asm.EntryPoint.resolve(EntryPoint.java:106)
	at com.garmin.monkeybrains.asm.Assembler.resolve(Assembler.java:1055)
	at com.garmin.monkeybrains.asm.Assembler.resolve(Assembler.java:860)
	at com.garmin.monkeybrains.asm.Assembler.assemble(Assembler.java:592)
	at com.garmin.monkeybrains.compiler.Compiler.assemble(Compiler.java:869)
	at com.garmin.monkeybrains.Monkeybrains.runCompiler(Monkeybrains.java:957)
	at com.garmin.monkeybrains.Monkeybrains.compileApplication(Monkeybrains.java:695)
	at com.garmin.monkeybrains.Monkeybrains.simpleMain(Monkeybrains.java:1567)
	at com.garmin.monkeybrains.Monkeybrains.main(Monkeybrains.java:1654)
ERROR: unknown:0: Unable to resolve entry class. Check the manifest file.
Makefile:45: recipe for target 'package' failed
make: *** [package] Error 100
```

```make build``` works fine.

Any ideas? 
While packaging the sme app with Eclipse CIQ plugin, I had no problems.

**Comment by danielsiwiec** [comment] 2017-04-19 08:06
@Artaud sorry for late response on this, but the issue is now fixed. we were missing an new line escape in one spot ;)

**Closed as completed** 2017-04-19 08:06 UTC

**Comment by Artaud** [comment] 2017-04-19 12:20
@danielsiwiec Damn I should've seen this one! Thanks :)
